# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# Configuration docs: /docs/dependabot-configuration.md

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" # Specify day for more predictable updates
      time: "09:00" # Optional: Set specific time (UTC)
    open-pull-requests-limit: 15 # Increased from 10 to accommodate security updates
    target-branch: "main" # Specify target branch explicitly
    reviewers:
      - "ken-guru"
      - "team:frontend-devs" # Optional team reviewer
    assignees:
      - "ken-guru" # Add assignees for better tracking
    # Enabled security updates  
    allow:
      - dependency-type: "all"
    vulnerability-alerts: true

    # Improved grouping strategy
    groups:
      dev-dependencies:
        patterns:
          - "*eslint*"
          - "*jest*"
          - "*test*"
          - "*prettier*"
          - "*babel*"
          - "*webpack*"
          - "*storybook*"
        update-types:
          - "minor"
          - "patch"
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "ts-*"
          - "*-typescript-*"
        update-types:
          - "minor"
          - "patch"
      linting-tools:
        patterns:
          - "*lint*"
          - "*prettier*"
          - "eslint-config-*"
          - "eslint-plugin-*"
        update-types:
          - "minor"
          - "patch"
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      next-ecosystem:
        patterns:
          - "next*"
          - "@next*"
        update-types:
          - "minor"
          - "patch"
      types:
        patterns:
          - "@types/*"
        exclude-patterns:
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"

    # Ignore certain dependencies or patterns
    ignore:
      # Example: Ignore major version updates for specific packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

    labels:
      - "dependencies"
      - "automerge"
      - "security:review" # Added for security-related updates
    
    # Configure refined automerge behavior
    automerge: true
    automerge-conditions:
      # Don't auto-merge critical dependencies
      - dependency-name: "!(react|next|react-dom)"
        update-type: "!(version-update:semver-major)"
    versioning-strategy: auto
    
    # Improved commit message format
    commit-message:
      prefix: "deps"
      prefix-development: "chore"
      include: "scope"
      # Format examples:
      # - deps(next): Update next.js dependencies from 13.1.0 to 13.2.0
      # - chore(eslint): Update eslint-config-next from 12.0.0 to 13.0.0

  # Add GitHub Actions ecosystem updates with enhanced configuration
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday" # Staggered from npm updates
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ken-guru"
    labels:
      - "ci-cd"
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
    automerge: true
